 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Adicionar Aluno</h3>
  
  <?php if(isset($view_error['warning'])){?>
  	<div><p><?php echo $view_error['warning']; ?></p></div>
  <?php } ?>
  	  	
  <form action="" method="POST">
  	<div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="nome">Nome</label>
  	  	<input type="text" class="form-control" name="nome" id="nome" placeholder="Digite o Nome do ALuno" value="<?php echo isset($view_aluno) ? $view_aluno : '';?>">
  	  	<?php if(isset($view_error['aluno'])){?>
  	  		<span> <?php echo $view_error['aluno']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="descricao">E-mail</label>
  	  	<input type="text" class="form-control" name="email" id="email" placeholder="Digite o e-mail" value="<?php echo isset($view_email) ? $view_email : '';?>">
  	    <?php if(isset($view_error['email'])){?>
  	  		<span> <?php echo $view_error['email']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="telefone">Telefone</label>
  	  	<input type="text" class="form-control" name="telefone" id="telefone" placeholder="Digite o telefone" value="<?php echo isset($view_telefone) ? $view_telefone : '';?>">
  	  </div>
  	  <?php if(isset($view_error['telefone'])){?>
  	  		<span> <?php echo $view_error['telefone']; ?></span>
  	  <?php } ?>
	</div>
	
	<div class="row">
  	  <div class="form-group col-md-3">
  	  	<label for="endereco">Endereço</label>
  	  	<input type="text" class="form-control" name="endereco" id="endereco" placeholder="Digite o endereco" value="<?php echo isset($view_endereco) ? $view_endereco : '';?>">
  	  </div>
  	  
	  <div class="form-group col-md-3">
  	  	<label for="cpf">CPF</label>
  	  	<input type="text" class="form-control" name="cpf" id="cpf" placeholder="Digite o cpf" value="<?php echo isset($view_cpf) ? $view_cpf : '';?>">
  	  	<?php if(isset($view_error['cpf'])){?>
  	  		<span> <?php echo $view_error['cpf']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-3">
  	  	<label for="id_usuario">ID Usuário</label>
  	  	<input type="text" class="form-control" name="id_usuario" id="id_usuario" placeholder="Digite a id_usuario" value="<?php echo isset($view_id_usuario) ? $view_id_usuario : '';?>">
		<?php if(isset($view_error['id_usuario'])){?>
  	  		<span> <?php echo $view_error['id_usuario']; ?></span>
  	  	<?php } ?>  	  
  	  </div>
 <div class="form-group col-md-3"> 	  
 <label for="imagem">Foto</label>
<form enctype="multipar/form-data"></form>
<input type="file" name="imagem"/>
  </div>


