 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Adicionar Aluno</h3>
  <img src="<?php echo $view_imagem; ?>" width="200" height="200"/> 	
  
    <?php if(isset($view_error['warning'])){?>
  	<div><p><?php echo $view_error['warning']; ?></p></div>
  <?php } ?>
  	  	
  <form action="" method="POST" enctype="multipart/form-data">
  	<div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="nome">Nome</label>
  	  	<input type="text" class="form-control" name="nome" id="nome" placeholder="Digite o Nome do ALuno" value="<?php echo isset($view_nome) ? $view_nome : '';?>">
  	  	<?php if(isset($view_error['nome'])){?>
  	  		<span> <?php echo $view_error['nome']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="email">E-mail</label>
  	  	<input type="text" class="form-control" name="email" id="email" placeholder="Digite o e-mail" value="<?php echo isset($view_email) ? $view_email : '';?>">
  	    <?php if(isset($view_error['email'])){?>
  	  		<span> <?php echo $view_error['email']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="telefone">Telefone</label>
  	  	<input type="text" class="form-control" name="telefone" id="telefone" placeholder="Digite o telefone" value="<?php echo isset($view_telefone) ? $view_telefone : '';?>">
  	  </div>
  	  <?php if(isset($view_error['telefone'])){?>
  	  		<span> <?php echo $view_error['telefone']; ?></span>
  	  <?php } ?>
	</div>
	
	<div class="row">
  	  <div class="form-group col-md-3">
  	  	<label for="endereco">Endereço</label>
  	  	<input type="text" class="form-control" name="endereco" id="endereco" placeholder="Digite o endereco" value="<?php echo isset($view_endereco) ? $view_endereco : '';?>">
  	  </div>
  	  
	  <div class="form-group col-md-3">
  	  	<label for="cpf">CPF</label>
  	  	<input type="text" class="form-control" name="cpf" id="cpf" placeholder="Digite o cpf" value="<?php echo isset($view_cpf) ? $view_cpf : '';?>">
  	  	<?php if(isset($view_error['cpf'])){?>
  	  		<span> <?php echo $view_error['cpf']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-3">
  	  	<label for="id_usuario">ID Usuário</label>
  	  	<input type="text" class="form-control" name="id_usuario" id="id_usuario" placeholder="Digite a id_usuario" value="<?php echo isset($view_id_usuario) ? $view_id_usuario : '';?>">
		<?php if(isset($view_error['id_usuario'])){?>
  	  		<span> <?php echo $view_error['id_usuario']; ?></span>
  	  	<?php } ?>  	  
  	  </div>
	 
	 <div class="form-group col-md-3">
	 	<label for="imagem">Foto</label>
		<input type="file" name="imagem"/>
		
		<?php if(isset($view_imagem)){?>
			<a href="<?php echo $view_imagem;?>" target="_blank">Visualizar Arquivo</a>
			<input type="hidden" name="imagem_existe" value="<?php echo $view_imagem?>" />
				
				<?php } ?>
		
		<?php if(isset($view_error['imagem'])){?>
  	  		<span> <?php echo $view_error['imagem']; ?></span>
  	  	<?php } ?>  	  
		
		
		
	 </div>
  
	<hr>
	<div class="row">
	  <div class="col-md-12">
	  	<button type="submit" class="btn btn-primary" name="submit" >Salvar</button>
		<a href="/Maestro2/alunos/alunos" class="btn btn-default">Cancelar</a>
	  </div>
	</div>
  </form>
 </div>


