<table class="table table-striped" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<th>ID</th>
					<th>Titulo</th>
					<th>Descrição</th>
					<th>Conteudo</th>
					<th>Professor</th>
					<th>Carga Horária</th>
					<th>Lotação</th>
					<th>Data Inicio</th>
					<th>Data Fim</th>
					<th class="actions">Ações</th>
				</tr>
			</thead>
			<tbody>
			
			<?php foreach ($view_cursos as $cursos){?>
				<tr>
					<td><?php echo $cursos['id']?></td>
					<td><?php echo $cursos['titulo']?></td>
					<td><?php echo $cursos['descricao']?></td>
					<td><?php echo $cursos['conteudo']?></td>
					<td><?php echo $cursos['professor']?></td>
					<td><?php echo $cursos['carga_horaria']?></td>
					<td><?php echo $cursos['lotacao']?></td>
					<td><?php echo $cursos['data_inicio']?></td>
					<td><?php echo $cursos['data_fim']?></td>
					<td class="actions">
						<a class="btn btn-warning btn-xs" href="/Maestro2/cursos/create">Editar</a>
						<a class="btn btn-danger btn-xs"  href="#" data-toggle="modal" data-target="#delete-modal">Excluir</a>
					</td>
				</tr>
			</tbody>
			<?php } ?>
		</table>
		<div class="col-md-12">
			<a href="/Maestro2/cursos/create" class="btn btn-default">Incluir Novo Curso</a>
	  	</div>