 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Adicionar Curso</h3>
  
  <form action="index.html">
  	<div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="titulo">Título do Curso</label>
  	  	<input type="text" class="form-control" id="titulo" placeholder="Digite o Título do Curso">
  	  </div>
	  <div class="form-group col-md-4">
  	  	<label for="descricao">Descrição</label>
  	  	<input type="text" class="form-control" id="descricao" placeholder="Digite uma breve descrição do curso">
  	  </div>
	  <div class="form-group col-md-4">
  	  	<label for="conteudo">Conteúdo</label>
  	  	<input type="text" class="form-control" id="conteudo" placeholder="Digite o Conteúdo">
  	  </div>
	</div>
	
	<div class="row">
  	  <div class="form-group col-md-3">
  	  	<label for="professor">Professor</label>
  	  	<input type="text" class="form-control" id="professor" placeholder="Digite o nome do Professor">
  	  </div>
	  <div class="form-group col-md-3">
  	  	<label for="carga_horaria">Carga Horária</label>
  	  	<input type="text" class="form-control" id="carga_horaria" placeholder="Digite a carga horária">
  	  </div>
	  <div class="form-group col-md-3">
  	  	<label for="lotacao">Lotação</label>
  	  	<input type="text" class="form-control" id="lotacao" placeholder="Digite a lotação">
  	  </div>
	  <div class="form-group col-md-3">
  	  	<label for="data_inicio">Data Início</label>
  	  	<input type="text" class="form-control" id="data_inicio" placeholder="Digite a data de início do curso">
  	  </div>
	</div>
	
	<div class="row">
  	  <div class="form-group col-md-6">
  	  	<label for="data_fim">Data Fim</label>
  	  	<input type="text" class="form-control" id="data_fim" placeholder="Digite a data do fim do curso">
  	  </div>
	</div>
	<hr />
	
	<div class="row">
	  <div class="col-md-12">
	  	<button type="submit" class="btn btn-primary">Salvar</button>
		<a href="template.html" class="btn btn-default">Cancelar</a>
	  </div>
	</div>
  </form>
 </div>