 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Adicionar Funcionario</h3>
  
  <?php if(isset($view_error['warning'])){?>
  	<div><p><?php echo $view_error['warning']; ?></p></div>
  <?php } ?>
  	  	
  <form action="" method="POST" enctype="multipart/form-data">
  	<div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="funcionario">Nome Funcionario</label>
  	  	<input type="text" class="form-control" name="funcionario" id="funcionario" placeholder="Digite o Nome do Funcionario" value="<?php echo isset($view_funcionario) ? $view_funcionario : '';?>">
  	  	<?php if(isset($view_error['funcionario'])){?>
  	  		<span> <?php echo $view_error['funcionario']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="funcao">Função</label>
  	  	<input type="text" class="form-control" name="funcao" id="funcao" placeholder="Digite a função" value="<?php echo isset($view_funcao) ? $view_funcao : '';?>">
  	    <?php if(isset($view_error['funcao'])){?>
  	  		<span> <?php echo $view_error['funcao']; ?></span>
  	  	<?php } ?>
  	  </div>
  	  
	  <div class="form-group col-md-4">
  	  	<label for="ativo">Ativo</label>
  	  	<input type="text" class="form-control" name="ativo" id="ativo" placeholder="Digite 1 p/ Ativo ou 0 p/ inativo" value="<?php echo isset($view_ativo) ? $view_ativo : '';?>">
  	  </div>
  	  <?php if(isset($view_error['ativo'])){?>
  	  		<span> <?php echo $view_error['ativo']; ?></span>
  	  <?php } ?>
	</div>
  	  
	  <div class="form-group col-md-3">
  	  	<label for="id_usuario">ID Usuário</label>
  	  	<input type="text" class="form-control" name="id_usuario" id="id_usuario" placeholder="Digite a id_usuario" value="<?php echo isset($view_id_usuario) ? $view_id_usuario : '';?>">
		<?php if(isset($view_error['id_usuario'])){?>
  	  		<span> <?php echo $view_error['id_usuario']; ?></span>
  	  	<?php } ?>  	  
  	  </div>
	 
	<hr>
	<div class="row">
	  <div class="col-md-12">
	  	<button type="submit" class="btn btn-primary" name="submit" >Salvar</button>
		<a href="/Maestro2/funcionario/funcionario" class="btn btn-default">Cancelar</a>
	  </div>
	</div>
  </form>
 </div>


